services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: codlab_bbs_db
    volumes:
      - codlab-bbs_db-data:/var/lib/mysql
  php:
    build: ./php
    depends_on:
      - db
    ports:
      - 8562:8000
    volumes:
      - ./work:/work
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_codlab_bbs
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
volumes:
  codlab-bbs_db-data:
  
